# Generated by Django 3.2.3 on 2024-03-06 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capcity', models.IntegerField(choices=[(1, '1-2 Guests'), (2, '3-4 Guests'), (3, '5-6 Guests'), (4, '7-8 Guests'), (5, '9-10 Guests'), (6, '11-12 Guests')])),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('num_guests', models.IntegerField()),
                ('time', models.CharField(choices=[('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00')], default='18:00', max_length=50)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
                ('table', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
